apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: audit
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/codenio/kubectl-audit/releases/download/{{ .TagName }}/audit_linux_amd64.tar.gz" .TagName }}
    files:
    - from: audit
      to: .
    - from: LICENSE
      to: .
    bin: audit
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/codenio/kubectl-audit/releases/download/{{ .TagName }}/audit_linux_arm64.tar.gz" .TagName }}
    files:
    - from: audit
      to: .
    - from: LICENSE
      to: .
    bin: audit
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/codenio/kubectl-audit/releases/download/{{ .TagName }}/audit_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: audit
      to: .
    - from: LICENSE
      to: .
    bin: audit
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/codenio/kubectl-audit/releases/download/{{ .TagName }}/audit_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: audit
      to: .
    - from: LICENSE
      to: .
    bin: audit
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/codenio/kubectl-audit/releases/download/{{ .TagName }}/audit_windows_amd64.zip" .TagName }}
    files:
    - from: audit.exe
      to: .
    - from: LICENSE
      to: .
    bin: audit.exe
  shortDescription: Run Kubernetes resource audits
  homepage: https://github.com/codenio/kubectl-audit
  caveats: |
    Usage:
      $ kubectl audit

    For additional options:
      $ kubectl audit --help
      or https://github.com/codenio/kubectl-audit/blob/{{ .TagName }}/doc/USAGE.md

  description: |
    Run quick Kubernetes resource audits for common operational issues, including
    non-running pods, NotReady/SchedulingDisabled nodes, non-Bound PVC/PV,
    failed jobs, and suspended cronjobs.
